table Produtos_EquipX
	lineageTag: 369887c4-34af-44db-a077-6711542cb58c

	column 'ID Produto'
		dataType: string
		lineageTag: 94e256e1-c6e1-4d49-98c0-d7aed279e630
		summarizeBy: none
		sourceColumn: ID Produto

		annotation SummarizationSetBy = Automatic

	column 'Nome produto'
		dataType: string
		lineageTag: e53ee325-00a2-49ad-b7cf-01ad0a3e8dee
		summarizeBy: none
		sourceColumn: Nome produto

		annotation SummarizationSetBy = Automatic

	column Categoria
		dataType: string
		lineageTag: 16f0f349-ddf5-4701-87fe-57be2b93443e
		summarizeBy: none
		sourceColumn: Categoria

		annotation SummarizationSetBy = Automatic

	column Marca
		dataType: string
		lineageTag: 6fb62f15-5096-45b4-8355-9cb229a0906c
		summarizeBy: none
		sourceColumn: Marca

		annotation SummarizationSetBy = Automatic

	column Valor
		dataType: string
		lineageTag: ab679e43-e0e2-4e4f-a846-591fe3e8b2d0
		summarizeBy: none
		sourceColumn: Valor

		annotation SummarizationSetBy = Automatic

	column 'URL Imagem'
		dataType: string
		lineageTag: 5c78c418-1970-4b22-8495-bb6ac76d4bef
		summarizeBy: none
		sourceColumn: URL Imagem

		annotation SummarizationSetBy = Automatic

	partition Produtos_EquipX = m
		mode: import
		source =
				let
				    Fonte = Json.Document(File.Contents(caminhoPasta & "Produtos_EquipX.json")),
				    #"Convertido para Tabela" = Table.FromList(Fonte, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Column1 Expandido" = Table.ExpandRecordColumn(#"Convertido para Tabela", "Column1", {"ID Produto", "Nome produto", "Categoria", "Marca", "Valor", "URL Imagem"}, {"ID Produto", "Nome produto", "Categoria", "Marca", "Valor", "URL Imagem"})
				in
				    #"Column1 Expandido"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

