table Vendas
	lineageTag: 6dbfdde6-9804-4294-a6d1-4eaf7a8317fd

	measure 'Total faturamento' = SUM(Vendas[Faturamento])
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: a799e96d-c761-472d-87bd-8f10ea204eb4

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column Transacao
		dataType: int64
		formatString: 0
		lineageTag: 7c607bd2-88d5-46ac-9395-aa40cc08b322
		summarizeBy: sum
		sourceColumn: Transacao

		annotation SummarizationSetBy = Automatic

	column 'Data de compra'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 695b29f6-e5f8-4b08-8058-b07ea7445907
		summarizeBy: none
		sourceColumn: Data de compra

		variation Variation
			isDefault
			relationship: 4f2b606e-1f18-4fdc-baff-e9fc79bfbc7b
			defaultHierarchy: LocalDateTable_90be4f2c-0e6f-4b19-977b-35598402e034.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'ID Consumidor'
		dataType: int64
		formatString: 0
		lineageTag: 2c2213dd-c641-4ef2-9f80-6b4d18c68056
		summarizeBy: none
		sourceColumn: ID Consumidor

		annotation SummarizationSetBy = Automatic

	column 'ID Produto'
		dataType: int64
		formatString: 0
		lineageTag: af2c0409-04cf-4791-8bcc-0f21a05a3fc3
		summarizeBy: none
		sourceColumn: ID Produto

		annotation SummarizationSetBy = Automatic

	column Quantidade
		dataType: int64
		formatString: 0
		lineageTag: c3553dad-048e-432a-b194-53ebed5a3e4d
		summarizeBy: sum
		sourceColumn: Quantidade

		annotation SummarizationSetBy = Automatic

	column Valor = LOOKUPVALUE(Produtos[Valor], Produtos[ID Produto], Vendas[ID Produto])
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 28b006f2-4d65-418f-a7f5-db4be829b44c
		summarizeBy: sum
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column Faturamento = Vendas[Quantidade]*Vendas[Valor]
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 45fa8dd1-f71b-41b4-b0b2-c641d61851dc
		summarizeBy: sum
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	partition Vendas = m
		mode: import
		source =
				let
				    Fonte = Folder.Files(caminhoPasta & "Vendas"),
				    #"Arquivos Ocultos Filtrados1" = Table.SelectRows(Fonte, each [Attributes]?[Hidden]? <> true),
				    #"Invocar Função Personalizada1" = Table.AddColumn(#"Arquivos Ocultos Filtrados1", "Transformar Arquivo", each #"Transformar Arquivo"([Content])),
				    #"Colunas Renomeadas1" = Table.RenameColumns(#"Invocar Função Personalizada1", {"Name", "Nome da Origem"}),
				    #"Outras Colunas Removidas1" = Table.SelectColumns(#"Colunas Renomeadas1", {"Nome da Origem", "Transformar Arquivo"}),
				    #"Coluna de Tabela Expandida1" = Table.ExpandTableColumn(#"Outras Colunas Removidas1", "Transformar Arquivo", Table.ColumnNames(#"Transformar Arquivo"(#"Arquivo de Amostra"))),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Coluna de Tabela Expandida1",{"Nome da Origem"}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Colunas Removidas",{{"Transacao", Int64.Type}, {"Data de compra", type date}, {"ID Consumidor", Int64.Type}, {"ID Produto", Int64.Type}, {"Quantidade", Int64.Type}}),
				    #"Linhas Filtradas" = Table.SelectRows(#"Tipo Alterado", each ([ID Produto] <> 13 and [ID Produto] <> 14 and [ID Produto] <> 15 and [ID Produto] <> 16 and [ID Produto] <> 17 and [ID Produto] <> 18 and [ID Produto] <> 19 and [ID Produto] <> 20))
				in
				    #"Linhas Filtradas"

	annotation PBI_ResultType = Table

